[package]
name = "malakai/maria"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.7"
Promise = "evaera/promise@4.0.0"
Streamable = "sleitnick/streamable@1.2.3"
Trove = "sleitnick/trove@0.4.1"
Signal = "sleitnick/signal@1.2.0"
Input = "sleitnick/input@2.0.0"
TableUtil = "sleitnick/table-util@1.1.4"